### ISSUE TITLE
Schermata bianca

### ISSUE THREAD

**Issue by MeerKatDev** [appfrontIT/lookinglass.github.io#1]
Ciao, dopo un po', andando avanti col processo, mi da' schermata bianca subito dopo la pagina "dati contratto"
cosa posso avere sbagliato?

<img width="1440" alt="Screenshot 2021-01-22 at 08 49 48" src="https://user-images.githubusercontent.com/1340996/105462597-21147680-5c8f-11eb-8079-5a11ab636a61.png">
sub

**Comment by appfrontIT** [comment]
Direi che ha perso l’autenticazione sulla sessione.
Potrebbero essere un problema su NGNIX.

Faccio subito un check.

Il giorno 22 gen 2021, alle ore 08:53, MeerKatDev <notifications@github.com> ha scritto:

﻿

Ciao, dopo un po', andando avanti col processo, mi da' schermata bianca subito dopo la pagina "dati contratto"
cosa posso avere sbagliato?

[Screenshot 2021-01-22 at 08 49 48]<https://user-images.githubusercontent.com/1340996/105462597-21147680-5c8f-11eb-8079-5a11ab636a61.png>

sub

**Comment by appfrontIT** [comment]
Ho riprovato la procedura e funziona. Probabilmente hai solo perso l'autenticazione. L'applicazione legacy in backend non ti avverte. Per cui meglio che riparti sempre dal login, se per un pochino di tempo non hai usato l'applicazione.

**Comment by MeerKatDev** [comment]
D'accordo, grazie

**Comment by MeerKatDev** [comment]
Altro problema:
<img width="1440" alt="Screenshot 2021-01-22 at 12 27 32" src="https://user-images.githubusercontent.com/1340996/105485514-4b752c80-5cad-11eb-8a89-ca6b872d1d84.png">

**Comment by appfrontIT** [comment]
Si è corretto.
Nella pagina precedente devi inserire la decorrenza della nuova polizza al 21/03/21.

Gian


Chief Technology Officer

[signature_1896473413]

Appfront srl
Via degli Olivetani 10/12, 20123 MILANO
Mobile. +39335330413
e-mail: it@appfront.cloud
web site: www.appfront.cloud<http://www.appfront.cloud/>


Da: MeerKatDev <notifications@github.com>
Data: venerdì, 22 gennaio 2021 12:28
A: appfrontIT/lookinglass.github.io <lookinglass.github.io@noreply.github.com>
Cc: IT Appfront <it@appfront.cloud>, Comment <comment@noreply.github.com>
Oggetto: Re: [appfrontIT/lookinglass.github.io] Schermata bianca (#1)

Altro problema:
[Screenshot 2021-01-22 at 12 27 32]<https://user-images.githubusercontent.com/1340996/105485514-4b752c80-5cad-11eb-8a89-ca6b872d1d84.png>
