### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by MeerKatDev** [appfrontIT/lookinglass.github.io#2]
Sarebbe un problema caricare il secondo file in questa repo nell'html? PRIMA di lookinglass.js.

Penso sarebbe meglio tenere i codici divisi, almeno per il momento.

**Comment by appfrontIT** [comment]
File caricato prima lookinglass.js

**Comment by MeerKatDev** [comment]
Grazie. Giusto come update, com'e' il formato? va bene? (e' solo fino alla pagina di anagrafica)
Provo a finire prima di mercoledi'
<img width="1440" alt="Screenshot 2021-01-25 at 19 37 55" src="https://user-images.githubusercontent.com/1340996/105750361-f5221b00-5f44-11eb-8169-6bfc605a842a.png">

**Comment by MeerKatDev** [comment]
Riesco ad arrivare fino ad Attestato di Rischio, poi compare 
"CODICE IUR GIÀ UTILIZZATO"

**Comment by appfrontIT** [comment]
Ciao Luca,

no purtroppo non va bene.

La mia idea era la seguente:

{
                User: <nome user>,
                SessionID: <prendiamo il cookie di jsessionID>,
                Inizio: <timestamp ISO esempio 2011-10-05T14:48:00.000Z>,
                Pagine: [
                               {
                                               url: <esempio https://ngnix.dallbogg.it/prodGrpList.do?_4VZD_=lVX&simulazione=S>,
                                               classePagina: prodGrpList.do,
                                               inizio: <timestamp ISO>,
                                               form: {}
                                },
                               {
                                               url: “https://ngnix.dallbogg.it/prodList.do?_C95_=VxY0fe&codgruppo=103”,
                                               classePagina: prodList.do,
                                               inizio: <timestamp ISO>,
                                               codgruppo: 103,
                                               form: {}

                                },
                               {
                                               url: https://ngnix.dallbogg.it/garanzieList.do?_DHfM8e_=f3Pop&codprod=203,
                                               classePagina: garanzieList.do
                                               sottoClassePagina: garanzie
                                               inizio: <timestamp ISO>,
                                               codprod: 203,
                                               form: {
                                                               tabella:[
                                                                               { Sel: true|false,
                                                                               Garanzia: RC.Veicoli,
                                                                               Oggetto: Autovettura/Autocarro 35Q,
name: “chk__00492”,
id: “checkbox1”,
value: <valore inserito>},     //in generale per ogni input salvare id, name, value
                                                                               { Sel: true|false,
                                                                               Garanzia: INC/Furto con Scoperto,
                                                                               Oggetto: Autovettura/Autocarro 35Q,
name: “”,
id: “”,
value: “”}
                                                               ],
                                                               Codice autorizzazione: “”
}
                               },
                               {
                                               url: https://ngnix.dallbogg.it/garanzieList.do?_pp2_=myV ,
                                               classePagina: garanzieList.do
                                               sottoClassePagina: anagrafica
                                               inizio: <timestamp ISO>,
                                               form: {
                                                               “Dati del contraente”:
{“Cognome e nome”: “”, //qui puoi lavorare solo sul risultato finale, senza gestire //la pagina di anagrafica dopo il pulsante “Seleziona”, quindi quando l’URL //diventa anagDetail.do
                                                                                              Indirizzo: “”,
                                                                                              …},
                                                               “Dati del proprietario del veicolo”:
                                                                                              {{“Cognome e nome”: “”,
                                                                                              Indirizzo: “”,
                                                                                              …},

}
                               },
                               {
                                               url: https://ngnix.dallbogg.it/anagEmissione.do?_X8Rb6_=0ic,
                                               classePagina: anagEmissione.do
                                               sottoClassePagina: questionario
                                               inizio: <timestamp ISO>,
                                               form: {
“QUESTIONARIO PER LA VALUTAZIONE DELL'ADEGUATEZZA DEI CONTRATTI AUTO E RAMI ELEMENTARI OFFERTI”: [
                                                               {Label: “Il contraente ha individuato l'esigenza per cui ritiene di assicurarsi ?”
                                                               id: “”,
                                                               name: “”,
                                                               value: “”
                                                               },

}
                               },
                               {
                                               url: https://ngnix.dallbogg.it/adeguatezza.do?_D5bI_=3wDNT&result=go,
                                               classePagina: adeguatezza.do
                                               sottoClassePagina: datiContratto
                                               inizio: <timestamp ISO>,
                                               form: [
                                                               {label: “”,
                                                               Name: “”,
                                                               Id: “”,
                                                               Value: “”},
                                                               {label: “”,
                                                               Name: “”,
                                                               Id: “”,
                                                               Value: “”},
                                               ]
                               },


L’oggetto form varia in funzione della classe della pagina. Attenzione che oltre i dati che inserisce l’utente in input, è necessario anche caricare i dati presentati in pagina (vedi ad esempio la pagina in cui viene visualizzata l’anagrafica contraente e proprietario).
Fammi sapere se è chiaro o se vogliamo organizzare una sessione in video

Gian




Chief Technology Officer

[signature_687502349]

Appfront srl
Via degli Olivetani 10/12, 20123 MILANO
Mobile. +39335330413
e-mail: it@appfront.cloud
web site: www.appfront.cloud<http://www.appfront.cloud/>


Da: MeerKatDev <notifications@github.com>
Data: lunedì, 25 gennaio 2021 19:39
A: appfrontIT/lookinglass.github.io <lookinglass.github.io@noreply.github.com>
Cc: IT Appfront <it@appfront.cloud>, Comment <comment@noreply.github.com>
Oggetto: Re: [appfrontIT/lookinglass.github.io] Testing (#2)

Grazie. Giusto come update, com'e' il formato? va bene? (e' solo fino alla pagina di anagrafica)
Provo a finire prima di mercoledi'
[Screenshot 2021-01-25 at 19 37 55]<https://user-images.githubusercontent.com/1340996/105750361-f5221b00-5f44-11eb-8169-6bfc605a842a.png>

**Comment by MeerKatDev** [comment]
E' molto chiaro, grazie per il formato, ma per il problema che ho scritto sopra non riesco ad andare oltre a quella pagina.

**Comment by appfrontIT** [comment]
Per la richiesta "Riesco ad arrivare fino ad Attestato di Rischio (puoi guardare gia' che funziona nel tuo tab), poi compare
"CODICE IUR GIÀ UTILIZZATO": non sono riuscito a replicare l'errore. Forse non hai inserito i dati esattamente come indicati nel video (o altra ipotesi c'è un errore nel video). Riusciamo a fare una condivisione schermo al volo?

**Comment by MeerKatDev** [comment]
I "confermo" del questionario suppongo non serva includerli, siccome devono essere selezionati per andare avanti. Prendo solo i Si e No.
